/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CS203.HW4;

/**
 *
 * @author harrison
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public GUI() {
        initComponents();
        orders.setVisible(false);
        coffees.setVisible(false);
        filteredCoffeesPanel.setVisible(false);
        espressoCoffeesPanel.setVisible(false);
        coffeesGroup.add(filteredCoffeeRadio);
        coffeesGroup.add(espressoRadio);
        filteredGroup.add(lightRadio);
        filteredGroup.add(mediumRadio);
        filteredGroup.add(darkRadio);
        espressoGroup.add(americanoRadio);
        espressoGroup.add(mochaRadio);
        espressoGroup.add(latteRadio);
        main.setVisible(false);
        addOns.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        coffeesGroup = new javax.swing.ButtonGroup();
        filteredGroup = new javax.swing.ButtonGroup();
        espressoGroup = new javax.swing.ButtonGroup();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        main = new javax.swing.JPanel();
        orderButton = new javax.swing.JButton();
        prepareButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        viewOrdersButton = new javax.swing.JButton();
        coffees = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();
        espressoRadio = new javax.swing.JRadioButton();
        filteredCoffeeRadio = new javax.swing.JRadioButton();
        filteredCoffeesPanel = new javax.swing.JPanel();
        lightRadio = new javax.swing.JRadioButton();
        mediumRadio = new javax.swing.JRadioButton();
        darkRadio = new javax.swing.JRadioButton();
        espressoCoffeesPanel = new javax.swing.JPanel();
        americanoRadio = new javax.swing.JRadioButton();
        mochaRadio = new javax.swing.JRadioButton();
        latteRadio = new javax.swing.JRadioButton();
        orders = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        exitOrdersButton = new javax.swing.JButton();
        name = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        nameClearButton = new javax.swing.JButton();
        nameSubmitButton = new javax.swing.JButton();
        addOns = new javax.swing.JPanel();
        whippedCheck = new javax.swing.JCheckBox();
        chocolateCheck = new javax.swing.JCheckBox();
        addOnsCancelButton = new javax.swing.JButton();
        addOnsSubmitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        orderButton.setText("Order");
        orderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderButtonActionPerformed(evt);
            }
        });

        prepareButton.setText("Prepare");

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        viewOrdersButton.setText("View Orders");
        viewOrdersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOrdersButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(orderButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prepareButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewOrdersButton, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(orderButton, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(viewOrdersButton, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(prepareButton, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        espressoRadio.setText("Espresso");
        espressoRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espressoRadioActionPerformed(evt);
            }
        });

        filteredCoffeeRadio.setText("Filtered Coffee");
        filteredCoffeeRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filteredCoffeeRadioActionPerformed(evt);
            }
        });

        lightRadio.setText("Light");

        mediumRadio.setText("Medium");
        mediumRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumRadioActionPerformed(evt);
            }
        });

        darkRadio.setText("Dark");

        javax.swing.GroupLayout filteredCoffeesPanelLayout = new javax.swing.GroupLayout(filteredCoffeesPanel);
        filteredCoffeesPanel.setLayout(filteredCoffeesPanelLayout);
        filteredCoffeesPanelLayout.setHorizontalGroup(
            filteredCoffeesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filteredCoffeesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(filteredCoffeesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lightRadio)
                    .addComponent(mediumRadio)
                    .addComponent(darkRadio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        filteredCoffeesPanelLayout.setVerticalGroup(
            filteredCoffeesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filteredCoffeesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lightRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mediumRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(darkRadio)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        americanoRadio.setText("Americano");

        mochaRadio.setText("Mocha");

        latteRadio.setText("Latte");

        javax.swing.GroupLayout espressoCoffeesPanelLayout = new javax.swing.GroupLayout(espressoCoffeesPanel);
        espressoCoffeesPanel.setLayout(espressoCoffeesPanelLayout);
        espressoCoffeesPanelLayout.setHorizontalGroup(
            espressoCoffeesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(espressoCoffeesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(espressoCoffeesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(americanoRadio)
                    .addComponent(mochaRadio)
                    .addComponent(latteRadio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        espressoCoffeesPanelLayout.setVerticalGroup(
            espressoCoffeesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(espressoCoffeesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(americanoRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mochaRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(latteRadio)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout coffeesLayout = new javax.swing.GroupLayout(coffees);
        coffees.setLayout(coffeesLayout);
        coffeesLayout.setHorizontalGroup(
            coffeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coffeesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(coffeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(coffeesLayout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitButton)
                        .addGap(20, 20, 20))
                    .addGroup(coffeesLayout.createSequentialGroup()
                        .addGroup(coffeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(filteredCoffeeRadio)
                            .addComponent(espressoRadio))
                        .addGap(18, 18, 18)
                        .addComponent(espressoCoffeesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filteredCoffeesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(27, Short.MAX_VALUE))))
        );
        coffeesLayout.setVerticalGroup(
            coffeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coffeesLayout.createSequentialGroup()
                .addGroup(coffeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(coffeesLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(espressoRadio)
                        .addGap(36, 36, 36)
                        .addComponent(filteredCoffeeRadio)
                        .addGap(0, 30, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, coffeesLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(coffeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(filteredCoffeesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(espressoCoffeesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(coffeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(submitButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jTextPane1);

        exitOrdersButton.setText("Exit");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(exitOrdersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exitOrdersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ordersLayout = new javax.swing.GroupLayout(orders);
        orders.setLayout(ordersLayout);
        ordersLayout.setHorizontalGroup(
            ordersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ordersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ordersLayout.setVerticalGroup(
            ordersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ordersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane2.setViewportView(jEditorPane1);

        jLabel1.setText("Name:");

        nameClearButton.setText("Clear");

        nameSubmitButton.setText("Submit");
        nameSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameSubmitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nameLayout = new javax.swing.GroupLayout(name);
        name.setLayout(nameLayout);
        nameLayout.setHorizontalGroup(
            nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nameLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(nameLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(nameLayout.createSequentialGroup()
                        .addComponent(nameClearButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nameSubmitButton)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        nameLayout.setVerticalGroup(
            nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nameLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameClearButton)
                    .addComponent(nameSubmitButton))
                .addContainerGap(176, Short.MAX_VALUE))
        );

        whippedCheck.setText("Whipped Cream");

        chocolateCheck.setText("Chocolate Syrup");

        addOnsCancelButton.setText("Cancel");
        addOnsCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOnsCancelButtonActionPerformed(evt);
            }
        });

        addOnsSubmitButton.setText("Submit");
        addOnsSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOnsSubmitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addOnsLayout = new javax.swing.GroupLayout(addOns);
        addOns.setLayout(addOnsLayout);
        addOnsLayout.setHorizontalGroup(
            addOnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addOnsLayout.createSequentialGroup()
                .addGroup(addOnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addOnsLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(addOnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(whippedCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chocolateCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(addOnsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addOnsCancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(addOnsSubmitButton)))
                .addContainerGap())
        );
        addOnsLayout.setVerticalGroup(
            addOnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addOnsLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(whippedCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chocolateCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(addOnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addOnsCancelButton)
                    .addComponent(addOnsSubmitButton))
                .addGap(19, 19, 19))
        );

        jDesktopPane1.setLayer(main, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(coffees, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(orders, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(name, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(addOns, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 382, Short.MAX_VALUE)
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(coffees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(orders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(addOns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 322, Short.MAX_VALUE)
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(coffees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(orders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(9, 9, 9)))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(addOns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewOrdersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOrdersButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewOrdersButtonActionPerformed

    private void orderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderButtonActionPerformed
        // TODO add your handling code here:
    main.setVisible(false);
    coffees.setVisible(true);
    }//GEN-LAST:event_orderButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        coffees.setVisible(false);
        main.setVisible(true);
        espressoGroup.clearSelection();
        filteredGroup.clearSelection();
        coffeesGroup.clearSelection();
        espressoCoffeesPanel.setVisible(false);
        filteredCoffeesPanel.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        coffees.setVisible(false);
        espressoGroup.clearSelection();
        filteredGroup.clearSelection();
        coffeesGroup.clearSelection();
        espressoCoffeesPanel.setVisible(false);
        filteredCoffeesPanel.setVisible(false);
        addOns.setVisible(true);
    }//GEN-LAST:event_submitButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void mediumRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumRadioActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mediumRadioActionPerformed

    private void filteredCoffeeRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filteredCoffeeRadioActionPerformed
        // TODO add your handling code here:
        if(filteredCoffeeRadio.isSelected()) {
            espressoCoffeesPanel.setVisible(false);
            espressoGroup.clearSelection();
            filteredCoffeesPanel.setVisible(true);
        }
    }//GEN-LAST:event_filteredCoffeeRadioActionPerformed

    private void espressoRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espressoRadioActionPerformed
        // TODO add your handling code here:
        if(espressoRadio.isSelected()){
            filteredCoffeesPanel.setVisible(false);
            filteredGroup.clearSelection();
            espressoCoffeesPanel.setVisible(true);
        }
    }//GEN-LAST:event_espressoRadioActionPerformed

    private void nameSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameSubmitButtonActionPerformed
        // TODO add your handling code here:
        name.setVisible(false);
        main.setVisible(true);
        this.setTitle(jEditorPane1.getText() + '\'' + " Order");
    }//GEN-LAST:event_nameSubmitButtonActionPerformed

    private void addOnsCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOnsCancelButtonActionPerformed
        // TODO add your handling code here:
        whippedCheck.setSelected(false);
        chocolateCheck.setSelected(false);
        addOns.setVisible(false);
        coffees.setVisible(true);
    }//GEN-LAST:event_addOnsCancelButtonActionPerformed

    private void addOnsSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOnsSubmitButtonActionPerformed
        // TODO add your handling code here:
        whippedCheck.setSelected(false);
        chocolateCheck.setSelected(false);
        addOns.setVisible(false);
        main.setVisible(true);
    }//GEN-LAST:event_addOnsSubmitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public void build() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Coffee tmp;
    private javax.swing.JPanel addOns;
    private javax.swing.JButton addOnsCancelButton;
    private javax.swing.JButton addOnsSubmitButton;
    private javax.swing.JRadioButton americanoRadio;
    private javax.swing.JButton cancelButton;
    private javax.swing.JCheckBox chocolateCheck;
    private javax.swing.JPanel coffees;
    private javax.swing.ButtonGroup coffeesGroup;
    private javax.swing.JRadioButton darkRadio;
    private javax.swing.JPanel espressoCoffeesPanel;
    private javax.swing.ButtonGroup espressoGroup;
    private javax.swing.JRadioButton espressoRadio;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton exitOrdersButton;
    private javax.swing.JRadioButton filteredCoffeeRadio;
    private javax.swing.JPanel filteredCoffeesPanel;
    private javax.swing.ButtonGroup filteredGroup;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JRadioButton latteRadio;
    private javax.swing.JRadioButton lightRadio;
    private javax.swing.JPanel main;
    private javax.swing.JRadioButton mediumRadio;
    private javax.swing.JRadioButton mochaRadio;
    private javax.swing.JPanel name;
    private javax.swing.JButton nameClearButton;
    private javax.swing.JButton nameSubmitButton;
    private javax.swing.JButton orderButton;
    private javax.swing.JPanel orders;
    private javax.swing.JButton prepareButton;
    private javax.swing.JButton submitButton;
    private javax.swing.JButton viewOrdersButton;
    private javax.swing.JCheckBox whippedCheck;
    // End of variables declaration//GEN-END:variables
}
